'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {SOURCES,parseRegionalTable}=require('../server/newsRegional.cjs');
const {regionalLoader,allowedPath,readText,declaredCharset,policyDelay}=require('../server/newsRegionalTransport.cjs');
const {robotAllows,createNewsServer}=require('../server/newsDataServer.cjs');
const NOW=Date.parse('2026-10-03T12:00:00Z');
function fixture(key,{count=SOURCES[key].count,season='2026-2027',points=14,played=8}={}){
 const rows=Array.from({length:count},(_,n)=>{const i=n+1,name='Club '+i,values=[played,4,2,2,12,9,3,points];
  if(key==='czech-second-league')return `<tr><td class="order">${i}</td><td></td><td><a href="/tymy/2026/${i}-club"><img alt="${name}" src="/photo/team/team_${i}.png">${name}</a></td>${values.map(x=>`<td>${x}</td>`).join('')}<td></td></tr>`;
  if(key==='austria-second-league'){const src='https://bundesliga-craftcms-production-bucket.s3.eu-central-1.amazonaws.com/clubs/'+i+'.png';return `<tr><td>${i}</td><td></td><td><a href="/team/club/${i}"><img alt="${name}" src="/_next/image?url=${encodeURIComponent(src)}"></a></td><td><p>${name}</p></td>${values.map(x=>`<td>${x}</td>`).join('')}<td></td><td></td><td></td></tr>`;}
  if(key==='turkey-first-league')return `<tr><td><a href="/Default.aspx?pageId=28&amp;kulupID=${i}">${i}.${name}</a></td>${values.map(x=>`<td>${x}</td>`).join('')}</tr>`;
  if(key==='serbia-prva-liga')return `<tr data-club-id="${i}"><td><span class="pos-deleg">${i}</span></td><td></td><td><a href="/club/${i}-club"><span class="team-name">${name}</span></a></td>${values.slice(0,7).map(x=>`<td>${x}</td>`).join('')}<td><span class="pts-wrapper">${points}</span></td></tr>`;
  return {year:+season.slice(0,4),leagueId:2,teamId:'K'+String(i).padStart(2,'0'),teamName:name,rank:i,gainPoint:points,winCnt:4,tieCnt:2,lossCnt:2,gapCnt:3,gainGoal:12,lossGoal:9,gameCount:played,stadium:'all'};
 });
 const header=a=>'<tr>'+a.map(x=>`<th>${x}</th>`).join('')+'</tr>';
 if(key==='czech-second-league')return `<title>Tabulka | Chance Národní Liga</title><select id="id_season"><option selected value="/tabulka/${season.slice(0,4)}">${season.replace('-','/')}</option></select><table class="standings__table">${header(['#','','Klub','Z','V','R','P','G+','G-','RG','B',''])}${rows.join('')}</table>`;
 if(key==='austria-second-league')return `<link rel="canonical" href="https://www.2liga.at/de/tabelle/saison-${season}"><h1>ADMIRAL 2. Liga Tabelle</h1><table>${header(['PL','Tendenz','','Klub','Spiele','S','U','N','Tore','GT','TD','Punkte','','',''])}${rows.join('')}</table>`;
 if(key==='turkey-first-league')return `<div class="moduleTitle">Trendyol 1. Lig ${season} Sezonu Puan Cetveli</div><table class="s-table">${header(['','O','G','B','M','A','Y','AV','P'])}${rows.join('')}</table>`;
 if(key==='serbia-prva-liga')return `<title>srbijasport.net - Fudbal - Muškarci - ${season} - Mozzart Bet Prva liga Srbije - Rezultati</title><a href="/league/8626-mozzart-bet-prva-liga-srbije">${season}</a><table class="ssnet-table" sport="football" league="8626" layout="standings"><tbody class="data">${rows.join('')}</tbody></table>`;
 return JSON.stringify({resultCode:'200',data:{year:+season.slice(0,4),isSplitRank:false,teamRank:rows,teamNameList:rows.map(r=>r.teamName+' FC'),teamNameShortList:rows.map(r=>({rank:r.rank,teamName:r.teamName}))}});
}
for(const key of Object.keys(SOURCES)){
 test(key+' exact current published table',()=>{const d=parseRegionalTable(fixture(key),key,NOW);assert.equal(d.rows.length,SOURCES[key].count);assert.equal(d.competition.id,key);assert.equal(d.rows[0].points,14);assert.equal(d.rows[0].played,8);assert.equal(d._newsRead.sourceUpdatedAt,null);assert.equal(d._newsRead.completeSeasonCoverageVerified,false);});
 test(key+' rejects old edition and malformed encoding',()=>{assert.throws(()=>parseRegionalTable(fixture(key,{season:'2025-2026'}),key,NOW));assert.throws(()=>parseRegionalTable(fixture(key)+'\uFFFD',key,NOW));});
 test(key+' refuses incomplete table and inconsistent stats',()=>{assert.throws(()=>parseRegionalTable(fixture(key,{count:SOURCES[key].count-1}),key,NOW));assert.throws(()=>parseRegionalTable(fixture(key,{played:9}),key,NOW));});
 test(key+' does not undo a publisher points deduction',()=>{const d=parseRegionalTable(fixture(key,{points:-2}),key,NOW);assert.equal(d.rows[0].points,-2);});
 test(key+' refuses another competition with plausible rows',()=>{const other=key==='serbia-prva-liga'?'turkey-first-league':'serbia-prva-liga';assert.throws(()=>parseRegionalTable(fixture(other),key,NOW));});
}
test('home and away tables cannot replace overall Austrian table',()=>{const a=fixture('austria-second-league'),table=a.slice(a.indexOf('<table>'));assert.equal(parseRegionalTable(a+'<div class="hidden">'+table+'</div>','austria-second-league',NOW).rows.length,16);assert.throws(()=>parseRegionalTable(a+table,'austria-second-league',NOW));});
test('image identity never accepts another team or outside origin',()=>{assert.throws(()=>parseRegionalTable(fixture('czech-second-league').replace('team_1.png','team_999.png'),'czech-second-league',NOW));assert.throws(()=>parseRegionalTable(fixture('austria-second-league').replaceAll('bundesliga-craftcms-production-bucket.s3.eu-central-1.amazonaws.com','evil.example'),'austria-second-league',NOW));});
test('wrong gender and same-sized other Turkish division fail',()=>{assert.throws(()=>parseRegionalTable(fixture('serbia-prva-liga').replace('Muškarci','Žene'),'serbia-prva-liga',NOW));assert.throws(()=>parseRegionalTable(fixture('turkey-first-league').replace('Trendyol 1. Lig','Trendyol Süper Lig'),'turkey-first-league',NOW));});
test('Korean split phase, wrong year or league, conflicting long-name list fail',()=>{for(const mutate of [d=>d.data.isSplitRank=true,d=>d.data.year=2025,d=>d.data.teamRank[0].leagueId=1,d=>d.data.teamNameShortList[0].teamName='different',d=>d.data.teamRank[1].teamId='K01']){const d=JSON.parse(fixture('south-korea-k-league-2'));mutate(d);assert.throws(()=>parseRegionalTable(JSON.stringify(d),'south-korea-k-league-2',NOW));}});
const resp=(body,status=200,type='text/html; charset=utf-8',extra={})=>new Response(body,{status,headers:{'content-type':type,...extra}});
test('only declared fixed paths accepted; no open proxy',()=>{for(const key of ['constructor','__proto__','unknown'])assert.equal(allowedPath(key,'https://www.chnliga.cz/tabulka'),false);for(const u of ['https://evil.example/tabulka','https://user:pass@www.chnliga.cz/tabulka','http://www.chnliga.cz/tabulka','https://www.chnliga.cz/tabulka?url=http://127.0.0.1','https://www.chnliga.cz/api/delete'])assert.equal(allowedPath('czech-second-league',u),false);assert.equal(allowedPath('south-korea-k-league-2','https://www.kleague.com/record/teamRank.do?leagueId=1&year=2026&stadium=all&recordType=rank'),false);});
test('declared Turkish encoding is lossless while broken UTF8 is rejected',async()=>{const b=Buffer.from([0xdd,0xfe,0xfd,0xf0]);const r=await readText(async()=>resp(b,200,'text/html; charset=windows-1254'),'turkey-first-league','https://www.tff.org/default.aspx?pageID=142');assert.equal(r.text,'İşığ');await assert.rejects(readText(async()=>resp(b),'turkey-first-league','https://www.tff.org/default.aspx?pageID=142'));assert.throws(()=>declaredCharset('text/html; charset=unsupported'));});
test('safe same-host source redirects are checked at each step',async()=>{const calls=[];const result=await readText(async u=>{calls.push(u);return calls.length===1?resp('',302,'text/html',{location:'/de/tabelle/saison-2026-2027'}):resp('table');},'austria-second-league','https://www.2liga.at/tabelle');assert.equal(result.text,'table');assert.equal(calls.length,2);let n=0;await assert.rejects(readText(async()=>{n++;return resp('',302,'text/html',{location:'http://127.0.0.1/secret'});},'austria-second-league','https://www.2liga.at/tabelle'));assert.equal(n,1);});
test('access denial remains denied; size and HTML robots never unlock source',async()=>{await assert.rejects(readText(async()=>resp('denied',403),'czech-second-league','https://www.chnliga.cz/robots.txt',{robots:true}));await assert.rejects(readText(async()=>resp('<html>home</html>'),'czech-second-league','https://www.chnliga.cz/robots.txt',{robots:true}));await assert.rejects(readText(async()=>resp('12345'),'czech-second-league','https://www.chnliga.cz/tabulka',{limit:4}));const r=await readText(async()=>resp('',404),'czech-second-league','https://www.chnliga.cz/robots.txt',{robots:true});assert.equal(r.text,'');});
test('source crawl delay honored and denial prevents fetching table',async()=>{let now=NOW,reads=[],pauses=[];const load=regionalLoader({clock:()=>now,robotAllows,logger:()=>{},sleep:async ms=>{pauses.push(ms);now+=ms;},fetcher:async u=>{reads.push(u);return u.endsWith('robots.txt')?resp('User-agent: *\nCrawl-delay: 10\nDisallow: /private',200,'text/plain'):resp(fixture('czech-second-league'));}});await load('czech-second-league');assert.deepEqual(pauses,[10000]);assert.equal(reads.length,2);let n=0;const deny=regionalLoader({robotAllows,logger:()=>{},fetcher:async()=>{n++;return resp('User-agent: *\nDisallow: /tabulka',200,'text/plain');}});await assert.rejects(deny('czech-second-league'));assert.equal(n,1);assert.throws(()=>policyDelay('Crawl-delay: 120'));});
test('concurrent callers share source reads; retained timestamp is never re-dated',async()=>{let now=NOW,reads=0,offline=false;const logs=[];const load=regionalLoader({clock:()=>now,robotAllows,logger:s=>logs.push(s),fetcher:async u=>{reads++;if(offline)throw Object.assign(Error('secret password'),{code:'ETIMEDOUT'});return u.endsWith('robots.txt')?resp('',404):resp(fixture('czech-second-league'));}});const [a,b]=await Promise.all([load('czech-second-league'),load('czech-second-league')]);assert.equal(a,b);assert.equal(reads,2);now+=16*60000;offline=true;const d=await load('czech-second-league');assert.equal(d.stale,true);assert.equal(d.updated_at,a.updated_at);const count=reads;await load('czech-second-league');assert.equal(reads,count);assert(!logs.join('').includes('secret'));now+=25*3600000;await assert.rejects(load('czech-second-league'));});
test('Korean request is a fixed public standings query, never user-directed POST',async()=>{const calls=[];const load=regionalLoader({clock:()=>NOW,robotAllows,logger:()=>{},fetcher:async(u,o)=>{calls.push({u,o});return u.endsWith('robots.txt')?resp('',404):resp(fixture('south-korea-k-league-2'),200,'application/json;charset=utf-8');}});assert.equal((await load('south-korea-k-league-2')).rows.length,17);assert.equal(calls[0].o.method,'GET');assert.equal(calls[1].o.method,'POST');assert.equal(calls[1].o.body,'');assert(calls[1].u.endsWith('?leagueId=2&year=2026&stadium=all&recordType=rank'));assert.equal(calls[1].o.credentials,'omit');});
test('only allowlisted NEWS routes use new readers, legacy success wins',async t=>{let primaryFails=false,calls=[];const server=createNewsServer({loader:async view=>{if(primaryFails)throw Error('source unavailable');return {source:'official-prva-liga',view};},regional:async key=>{calls.push(key);return parseRegionalTable(fixture(key),key,NOW);}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base='http://127.0.0.1:'+server.address().port;let r=await fetch(base+'/news-data/football/serbia-prva-liga/standings');assert.equal((await r.json()).source,'official-prva-liga');assert.deepEqual(calls,[]);primaryFails=true;for(const key of Object.keys(SOURCES)){r=await fetch(base+'/news-data/football/'+key+'/standings');assert.equal(r.status,200);assert.equal((await r.json()).competition.id,key);}for(const route of ['/news-data/football/czech-second-league/matches','/news-data/football/unknown/standings','/news-data/football/serbia-prva-liga/standings?url=http://127.0.0.1'])assert.equal((await fetch(base+route)).status,404);assert.equal((await fetch(base+'/news-data/football/czech-second-league/standings',{method:'POST'})).status,405);assert.equal((await fetch(base+'/news-data/football/serbia-prva-liga/matches')).status,503);});
