import {it,expect,vi,afterEach} from 'vitest';
import {parseNewsSourceBoard,loadNewsSourceMatches,clearNewsFixtureCache} from './newsFixtureSupplement.js';
const menu='spain-la-liga-2',spec={uid:'s:600~l:3921',slug:'esp.2',name:'Spanish LALIGA 2'},table={competition:{id:menu,sport:'football'},season:'2026/2027',_newsRead:{supplementary:true}},now=Date.parse('2026-10-03T10:00Z');
function board(year=2026){const id='1001',uid=spec.uid+'~e:'+id,date=year===2026?'2026-09-01T16:00Z':'2027-01-03T20:00Z',status=year===2026?{state:'post',completed:true,name:'STATUS_FULL_TIME'}:{state:'pre',completed:false,name:'STATUS_SCHEDULED'};return {leagues:[spec],events:[{id,uid,date,season:{year:2026},competitions:[{id,uid:uid+'~c:'+id,date,timeValid:year===2026,status:{type:status},competitors:[{homeAway:'home',type:'team',score:'0',team:{id:'2',uid:'s:600~t:2',displayName:'Club A',logo:'https://a.espncdn.com/2.png'}},{homeAway:'away',type:'team',score:'2',team:{id:'3',uid:'s:600~t:3',displayName:'Club B',logo:'https://a.espncdn.com/3.png'}}]}]}]};}
const parse=d=>parseNewsSourceBoard(d,menu,spec,table,2026,now),response=d=>({ok:true,status:200,headers:new Headers({'content-type':'application/json'}),text:async()=>JSON.stringify(d)});
afterEach(clearNewsFixtureCache);
it('retains real nil score and source event identity without mutation',()=>{const raw=board(),before=JSON.stringify(raw),d=parse(raw);expect(d[0]).toMatchObject({score:{home:0,away:2},status:'finished',details_available:false,season:'2026/2027'});expect(d[0].key).toBe('news-espn:1001');expect(JSON.stringify(raw)).toBe(before);});
it('scheduled zero placeholders are not scores or exact kickoff times',()=>{const d=parseNewsSourceBoard(board(2027),menu,spec,table,2027,now);expect(d[0].score).toEqual({home:null,away:null});expect(d[0].start_precision).toBe('DATE_ONLY');expect(d[0].source_date).toBe('2027-01-03');});
it.each(['league','event','competition','team','status','score','date','duplicate'])('rejects incorrect %s',field=>{const raw=board(),e=raw.events[0],c=e.competitions[0];if(field==='league')raw.leagues[0]={...spec,uid:'other'};if(field==='event')e.uid='other';if(field==='competition')c.uid='other';if(field==='team')c.competitors[0].team.uid='wrong';if(field==='status')c.status.type={state:'nonsense',completed:false};if(field==='score')c.competitors[0].score='';if(field==='date')e.date='2025-01-01';if(field==='duplicate')raw.events.push(e);expect(()=>parse(raw)).toThrow();});
it('does not mix sporting seasons inside one calendar-year response',()=>{const d=board();d.events[0].season.year=2025;expect(parse(d)).toEqual([]);});
it('reads at most two season years and reuses the complete cached records',async()=>{const next=board(2027);next.events[0].id='2001';next.events[0].uid=spec.uid+'~e:2001';next.events[0].competitions[0].id='2001';next.events[0].competitions[0].uid=spec.uid+'~e:2001~c:2001';const fetcher=vi.fn().mockResolvedValueOnce(response(board())).mockResolvedValueOnce(response(next)),d=await loadNewsSourceMatches(menu,spec,{fetcher,now},async()=>table);expect(d.events).toHaveLength(2);expect(fetcher).toHaveBeenCalledTimes(2);expect(fetcher.mock.calls.map(c=>c[0])).toEqual([2026,2027].map(y=>`https://site.web.api.espn.com/apis/site/v2/sports/soccer/esp.2/scoreboard?dates=${y}&limit=1000`));await loadNewsSourceMatches(menu,spec,{fetcher,now},async()=>table);expect(fetcher).toHaveBeenCalledTimes(2);});
it('never treats one failed season-year as a complete season and backs off',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(board())).mockRejectedValue(Error('unavailable'));await expect(loadNewsSourceMatches(menu,spec,{fetcher,now},async()=>table)).rejects.toThrow();await expect(loadNewsSourceMatches(menu,spec,{fetcher,now:now+1000},async()=>table)).rejects.toThrow();expect(fetcher).toHaveBeenCalledTimes(2);});
it('does not silently accept a response at the maximum record limit',()=>{const d=board();d.events=Array(1000).fill(d.events[0]);expect(()=>parse(d)).toThrow();});
