import {it,expect,vi,afterEach} from 'vitest';
import {NEWS_TABLE_SOURCES,parseNewsSourceTable,loadNewsSupplement,newsTableSourceURL,clearNewsSupplementCache} from './newsFootballSupplement.js';
import {readNewsData} from './newsFootballData.js';
const now=Date.parse('2026-10-03T10:00Z'),key='england-championship';
function fixture(menu=key,year=2026){
 const spec=NEWS_TABLE_SOURCES[menu],uid=spec.uid,stats={gamesPlayed:3,wins:1,ties:1,losses:1,pointsFor:5,pointsAgainst:4,pointDifferential:1,points:4,rank:1,deductions:0};
 return {uid,name:spec.name,season:{year,displayName:`${year}-${String(year+1).slice(-2)} ${spec.name}`,startDate:`${year}-07-01T00:00:00Z`,endDate:`${year+1}-07-01T00:00:00Z`},seasons:[],children:[{uid:uid+'~g:1',name:'League Phase',abbreviation:`${year}-${String(year+1).slice(-2)}`,standings:{season:year,seasonType:1,links:[{href:`https://www.espn.com/soccer/table/_/league/${spec.slug}`}],entries:Array.from({length:spec.min},(_,i)=>({team:{id:String(i+1),uid:`s:600~t:${i+1}`,displayName:`Club ${i+1}`,logos:[{href:`https://a.espncdn.com/i/teamlogos/soccer/500/${i+1}.png`}]},stats:Object.entries({...stats,rank:i+1}).map(([name,value])=>({name,value}))}))}}]};
}
const response=raw=>({ok:true,status:200,headers:new Headers({'content-type':'application/json'}),text:async()=>JSON.stringify(raw)});
const empty={competition:{id:key,sport:'football'},rows:[],events:[],stale:true};
afterEach(()=>{clearNewsSupplementCache();vi.useRealTimers();});
it.each(Object.keys(NEWS_TABLE_SOURCES))('validates the explicitly identified %s table',menu=>{const raw=fixture(menu),before=JSON.stringify(raw),d=parseNewsSourceTable(raw,menu,{now});expect(d.rows).toHaveLength(NEWS_TABLE_SOURCES[menu].min);expect(d.rows[0]).toMatchObject({played:3,wins:1,draws:1,losses:1,points:4,goals_for:5,goals_against:4,goal_difference:1});expect(JSON.stringify(raw)).toBe(before);expect(d._newsRead.completeSeasonCoverageVerified).toBe(false);});
it.each(['uid','name'])('rejects wrong source %s',field=>{const d=fixture();d[field]='wrong';expect(()=>parseNewsSourceTable(d,key,{now})).toThrow();});
it.each(['uid','links','season'])('rejects wrong child %s',field=>{const d=fixture();if(field==='uid')d.children[0].uid='s:600~l:999~g:1';else d.children[0].standings[field]=field==='links'?[{href:'https://evil.test/league/eng.2'}]:2025;expect(()=>parseNewsSourceTable(d,key,{now})).toThrow();});
it('does not relabel previous CAF groups using current wrapper year',()=>{const d=fixture('caf-champions-league');d.children[0].name='2025-26 CAF Champions League Group A';expect(()=>parseNewsSourceTable(d,'caf-champions-league',{now})).toThrow();});
it('labels archived editions and rejects a mismatched requested season',()=>{const d=fixture('fifa-club-world-cup',2025),result=parseNewsSourceTable(d,'fifa-club-world-cup',{now});expect(result.season).toBe('2025/2026');expect(result._newsRead.historical).toBe(true);expect(()=>parseNewsSourceTable(fixture(key,2025),key,{now})).toThrow();expect(()=>parseNewsSourceTable(d,'fifa-club-world-cup',{season:'2026/2027',now})).toThrow();});
it.each(['rank','gamesPlayed','wins','ties','losses','pointsFor','pointsAgainst','pointDifferential','points'])('requires actual %s rather than zero filling',name=>{const d=fixture();d.children[0].standings.entries[0].stats=d.children[0].standings.entries[0].stats.filter(s=>s.name!==name);expect(()=>parseNewsSourceTable(d,key,{now})).toThrow();});
it('preserves reported points and deductions without recomputing points',()=>{const d=fixture(),s=d.children[0].standings.entries[0].stats;s.find(s=>s.name==='points').value=1;s.find(s=>s.name==='deductions').value=3;expect(parseNewsSourceTable(d,key,{now}).rows[0]).toMatchObject({points:1,points_deduction:3});});
it.each(['duplicate-team','duplicate-rank','incorrect-played','incorrect-goal-difference','short-table','missing-group','string-number'])('rejects %s',kind=>{const d=fixture(),entries=d.children[0].standings.entries;if(kind==='duplicate-team')entries[1].team=entries[0].team;if(kind==='duplicate-rank')entries[1].stats.find(s=>s.name==='rank').value=1;if(kind==='incorrect-played')entries[0].stats.find(s=>s.name==='gamesPlayed').value=90;if(kind==='incorrect-goal-difference')entries[0].stats.find(s=>s.name==='pointDifferential').value=99;if(kind==='short-table')entries.pop();if(kind==='missing-group')d.children=[];if(kind==='string-number')entries[0].stats.find(s=>s.name==='points').value='4';expect(()=>parseNewsSourceTable(d,key,{now})).toThrow();});
it('does not request unknown sources or arbitrary URLs',async()=>{const fetcher=vi.fn();expect(await loadNewsSupplement('unknown','standings',{fetcher})).toBeNull();expect(await loadNewsSupplement(key,'unsupported-view',{fetcher})).toBeNull();expect(fetcher).not.toHaveBeenCalled();expect(newsTableSourceURL('https://evil.test')).toBeNull();expect(()=>newsTableSourceURL(key,'2026&x=1')).toThrow();});
it('uses anonymous cached GETs without site cookies',async()=>{const fetcher=vi.fn().mockResolvedValue(response(fixture())),a=await loadNewsSupplement(key,'standings',{fetcher,now}),b=await loadNewsSupplement(key,'standings',{fetcher,now:now+60000});expect(a).toBe(b);expect(fetcher).toHaveBeenCalledTimes(1);expect(fetcher.mock.calls[0][1]).toMatchObject({method:'GET',credentials:'omit',mode:'cors',redirect:'error',referrerPolicy:'no-referrer'});});
it('backs off failures but does not cache cancellation',async()=>{const fetcher=vi.fn().mockRejectedValue(Error('offline'));await expect(loadNewsSupplement(key,'standings',{fetcher,now})).rejects.toThrow();await expect(loadNewsSupplement(key,'standings',{fetcher,now:now+5000})).rejects.toThrow();expect(fetcher).toHaveBeenCalledTimes(1);clearNewsSupplementCache();const c=new AbortController();c.abort();await expect(loadNewsSupplement(key,'standings',{fetcher,now,signal:c.signal})).rejects.toMatchObject({name:'AbortError'});expect(fetcher).toHaveBeenCalledTimes(1);});
it('settles cancellation even when fetch ignores it',async()=>{const c=new AbortController(),fetcher=vi.fn(()=>new Promise(()=>{})),p=loadNewsSupplement(key,'standings',{signal:c.signal,fetcher,now});c.abort();await expect(p).rejects.toMatchObject({name:'AbortError'});});
it('retains a fresh populated primary table without an extra request',async()=>{const d={...empty,rows:[{team:'Existing',points:0}],stale:false},supplement=vi.fn();expect(await readNewsData(vi.fn().mockResolvedValue(d),key,'standings',{supplement})).toBe(d);expect(supplement).not.toHaveBeenCalled();});
it('fills empty or failed primary reads from valid scoped source',async()=>{const d=parseNewsSourceTable(fixture(),key,{now}),supplement=vi.fn().mockResolvedValue(d);for(const get of [vi.fn().mockResolvedValue(empty),vi.fn().mockRejectedValue(Error('offline'))])expect(await readNewsData(get,key,'standings',{supplement,now})).toBe(d);});
it('keeps old nonempty primary data when the supplement fails',async()=>{const d={...empty,rows:[{team:'Existing',points:5}]},supplement=vi.fn().mockRejectedValue(Error('source offline'));expect((await readNewsData(vi.fn().mockResolvedValue(d),key,'standings',{supplement})).rows).toEqual(d.rows);await expect(readNewsData(vi.fn().mockResolvedValue(empty),key,'standings',{supplement})).rejects.toThrow('source offline');});
it('rejects foreign key or season from supplemental reader',async()=>{for(const extra of [{...empty,competition:{id:'spain-la-liga',sport:'football'},rows:[{}]},{...empty,season:'2025/2026',rows:[{}]}])await expect(readNewsData(vi.fn().mockResolvedValue(empty),key,'standings',{season:'2026/2027',supplement:async()=>extra})).rejects.toThrow();});
it('rereads the exact previous CAF edition rather than relabelling it',async()=>{const k='caf-champions-league',raw=fixture(k);raw.children[0].name='2025-26 CAF Champions League Group A';const fetcher=vi.fn().mockResolvedValueOnce(response(raw)).mockResolvedValueOnce(response(fixture(k,2025))),d=await loadNewsSupplement(k,'standings',{fetcher,now});expect(fetcher.mock.calls[1][0]).toContain('?season=2025');expect(d.season).toBe('2025/2026');expect(d._newsRead).toMatchObject({edition:true,historical:true,currentEditionUnavailable:true});});
it('does not replace an explicit current-season request with a CAF archive',async()=>{const k='caf-champions-league',raw=fixture(k);raw.children[0].name='2025-26 CAF Champions League Group A';const fetcher=vi.fn().mockResolvedValue(response(raw));await expect(loadNewsSupplement(k,'standings',{fetcher,now,season:'2026/2027'})).rejects.toThrow();expect(fetcher).toHaveBeenCalledTimes(1);});
