'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {parseRegionalTable,SPECS}=require('../server/newsRegionalTables.cjs');
const {snapshotLoader,validateSnapshot}=require('../server/newsSnapshotServer.cjs');
const NOW=Date.parse('2026-10-03T11:00Z');
function czech(){const spec=SPECS['czech-second-league'];return `<meta property="og:site_name" content="Chance Národní Liga"><meta property="og:url" content="${spec.origin}/tabulka"><select name="id_season"><option selected value="/tabulka/2026">2026/2027</option></select><table class="standings__table"><tr>${['#','','Klub','Z','V','R','P','G+','G-','RG','B',''].map(s=>'<th>'+s+'</th>').join('')}</tr>${Array.from({length:16},(_,i)=>'<tr>'+[i+1,'',`<img src="/photo/team/team_${i+1}.png" alt="Club ${i+1}"><a href="/tymy/2026/${i+1}-club">Club ${i+1}</a>`,9,5,1,3,12,11,1,16,''].map(s=>'<td>'+s+'</td>').join('')+'</tr><tr><td colspan="12"></td></tr>').join('')}</table>`;}
function austria(){const image=id=>'/_next/image?url='+encodeURIComponent('https://bundesliga-craftcms-production-bucket.s3.eu-central-1.amazonaws.com/craft-cms-oefbl/Klubs/Icons/'+id+'.png')+'&w=128&q=75';const rows=Array.from({length:16},(_,i)=>'<tr>'+[i+1,'',`<a href="/team/club/${i+1}"><img alt="Club ${i+1}" src="${image(i+1)}"></a>`,'CLB Club '+(i+1),9,5,1,3,12,11,1,16,'','',''].map(s=>'<td>'+s+'</td>').join('')+'</tr>').join('');const table='<table><tr>'+['PL','Tendenz','','Klub','Spiele','S','U','N','Tore','GT','TD','Punkte','','',''].map(s=>'<th>'+s+'</th>').join('')+'</tr>'+rows+'</table>';return '<link rel="canonical" href="https://www.2liga.at/de/tabelle"><h1>ADMIRAL 2. Liga Tabelle</h1><button aria-haspopup="menu">2026 / 2027</button><button>Gesamt</button><button>Heim</button><button>Auswärts</button>'+table+table+table;}
function snapshot(key='czech-second-league'){const standings=parseRegionalTable(key==='czech-second-league'?czech():austria(),key,NOW);return {version:1,competition:key,source:standings.source,checked_at:new Date(NOW).toISOString(),standings};}
for(const key of Object.keys(SPECS))test('retains actual full table, including qualified names, '+key,()=>{const d=snapshot(key);assert.equal(d.standings.rows.length,16);assert.equal(d.standings.rows[0].points,16);assert.equal(d.standings.rows[0].played,9);assert.equal(d.standings.rows[0].goal_difference,1);assert.equal(validateSnapshot(d,key,NOW).stale,false);});
for(const [from,to] of [['2026/2027','2025/2026'],['/tabulka','/other'],['Chance Národní Liga','First League'],['<td>9</td>','<td>10</td>'],['team_1.png','team_2.png'],['<th>G+</th>','<th>Other</th>']])test('Czech parser rejects changed '+from,()=>assert.throws(()=>parseRegionalTable(czech().replace(from,to),'czech-second-league',NOW)));
for(const [from,to] of [['Gesamt','Heim'],['2026 / 2027','2025 / 2026'],['ADMIRAL 2. Liga Tabelle','Bundesliga'],['/Icons%2F1.png','/Icons%2F999.png'],['<td>12</td>','<td>14</td>']])test('Austrian parser rejects changed '+from,()=>{let raw=austria();const literal=from==='/Icons%2F1.png'?'%2FIcons%2F1.png':from;assert(raw.includes(literal));assert.throws(()=>parseRegionalTable(raw.replace(literal,to),'austria-second-league',NOW));});
test('Austrian home and away views are not concatenated into a false 48-team table',()=>assert.equal(parseRegionalTable(austria(),'austria-second-league',NOW).rows.length,16));
for(const [kind,change] of [['old',d=>d.checked_at=new Date(NOW-25*3600000).toISOString()],['future',d=>d.checked_at=new Date(NOW+3600000).toISOString()],['foreign',d=>d.competition='spain-la-liga'],['missing-stat',d=>delete d.standings.rows[0].points],['wrong-source',d=>d.standings.source='unknown'],['unsafe-image',d=>d.standings.rows[0].logo='https://evil.example/logo.png'],['duplicate',d=>d.standings.rows[1].team_id=d.standings.rows[0].team_id]])test('snapshot rejects '+kind,()=>{const d=snapshot();change(d);assert.throws(()=>validateSnapshot(d,'czech-second-league',NOW));});
test('old but retained data preserves the real successful read timestamp',()=>{const d=snapshot();assert.equal(validateSnapshot(d,'czech-second-league',NOW+3*3600000).stale,true);assert.equal(d.checked_at,new Date(NOW).toISOString());});
test('delivery uses only the owned data branch, shares pending fetch and never sends cookies',async()=>{const calls=[],fetcher=async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify(snapshot()),{headers:{'content-type':'text/plain'}});};const load=snapshotLoader({fetcher,clock:()=>NOW}),[a,b]=await Promise.all([load('czech-second-league','standings'),load('czech-second-league','standings')]);assert.equal(a.rows.length,16);assert.equal(b.rows.length,16);assert.equal(calls.length,1);assert.equal(calls[0].url,'https://raw.githubusercontent.com/macamala/allball-frontend/news-official-data/czech-second-league.json');assert.equal(calls[0].options.credentials,'omit');assert.equal(calls[0].options.redirect,'error');});
test('unavailable snapshots never become fabricated data',async()=>{let now=NOW,failed=false;const load=snapshotLoader({clock:()=>now,fetcher:async()=>{if(failed)throw Error('offline');return new Response(JSON.stringify(snapshot()),{headers:{'content-type':'text/plain'}});}});const d=await load('czech-second-league','standings');failed=true;now+=3*3600000;const retained=await load('czech-second-league','standings');assert(retained.stale);assert.equal(retained.updated_at,d.updated_at);now+=25*3600000;await assert.rejects(load('czech-second-league','standings'));});
test('unknown routes and unsupported regional fixtures perform no requests',async()=>{let calls=0;const load=snapshotLoader({fetcher:()=>{calls++;throw Error('unexpected');}});await assert.rejects(load('unknown','standings'));await assert.rejects(load('czech-second-league','matches'));assert.equal(calls,0);});
test('refresh respects crawl delay and refuses denied source, without partial source overwrite',async()=>{const {refresh}=require('../scripts/refresh-news-official.cjs');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'news-data-')),reportFile=path.join(dir,'serbia-prva-liga.json');fs.writeFileSync(reportFile,'old snapshot');const waits=[],reads=[];const report=await refresh(dir,{clock:()=>NOW,wait:async ms=>waits.push(ms),fetcher:async url=>{reads.push(url);if(url.includes('prvaliga.rs'))return new Response('denied',{status:403,headers:{'content-type':'text/plain'}});if(url.endsWith('robots.txt'))return new Response('User-agent: *\nAllow: /\n'+(url.includes('chnliga')?'Crawl-delay: 10':''),{headers:{'content-type':'text/plain'}});return new Response(url.includes('chnliga')?czech():austria(),{headers:{'content-type':'text/html'}});}});assert.equal(report.sources[0].status,'failed');assert.equal(report.sources[1].status,'updated');assert.equal(report.sources[2].status,'updated');assert.deepEqual(waits,[10000]);assert.equal(reads.filter(u=>u.includes('prvaliga')).length,1);assert.equal(fs.readFileSync(reportFile,'utf8'),'old snapshot');assert(!fs.readdirSync(dir).some(p=>p.endsWith('.html')));fs.rmSync(dir,{recursive:true,force:true});});
