'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {parseStandings,parseMatches,kickoff,ORIGIN,PATHS}=require('../server/newsPrva.cjs');
const {officialLoader,createNewsServer,robotAllows}=require('../server/newsDataServer.cjs');
const NOW=Date.parse('2026-10-03T10:30Z'),crest=id=>`<img src="${ORIGIN}/wp-content/themes/newweb-theme/images/grbovi/${id}.svg">`;
function shell(view,body){return `<link rel="canonical" href="${ORIGIN+PATHS[view]}"><a>Sezona 26/27</a><img id="logo_img" src="${ORIGIN}/wp-content/themes/newweb-theme/images/MPLS-logo-h.svg" alt="Prva liga Srbije">${body}`;}
function table(){const head=['POZ.','KLUB','ODIG.','POB.','NER.','POR.','DATO','PRIM.','RAZ.','BOD.'];return shell('standings',`<table class="preliminarno"><thead><tr>${head.map(h=>'<th>'+h+'</th>').join('')}</tr></thead><tbody>${Array.from({length:16},(_,i)=>'<tr>'+[i+1,crest(i+1),'Club '+(i+1),11,4,3,4,15,14,1,15].map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')}</tbody></table>`);}
function schedule(){let rows='';for(let round=1;round<=30;round++){rows+=`<div id="kolo-${round}">`;for(let i=0;i<8;i++){const part=cls=>`<div class="${cls}">`;rows+=`<div class="widget-single-match"><div class="match-date">INVALID MOBILE COPY</div><div class="match-participants">${part('match-date')}10.10.2026</div>${part('match-time')}--:--</div>${part('match-bagde')}Planirano</div>${part('match-home')}Club ${i*2+1}</div>${part('match-team-logo')}${crest(i*2+1)}</div>${part('match-result')}:</div>${part('match-team-logo')}${crest(i*2+2)}</div>${part('match-away')}Club ${i*2+2}</div>${part('match-venue')}Public stadium</div></div></div>`;}rows+='</div>';}return shell('matches','<h2 class="title">Raspored i rezultati 2026/27</h2>'+rows);}
const response=(body,status=200,type='text/html')=>new Response(body,{status,headers:{'content-type':type}});
test('full table retains exact source columns and points',()=>{const d=parseStandings(table(),NOW);assert.equal(d.rows.length,16);assert.equal(d.rows[0].points,15);assert.equal(d.rows[0].played,11);assert.equal(d.rows[0].goal_difference,1);assert.equal(d.season,'2026/2027');assert.equal(d.table_status,'provisional');assert.equal(d.competition.id,'serbia-prva-liga');});
for(const [name,from,to] of [['canonical','/sezona/tebela-takmicenja/','/wrong/'],['logo','MPLS-logo-h.svg','UEFA.svg'],['season','Sezona 26/27','Sezona 25/26'],['column','<th>POB.</th>',''],['crest','grbovi/1.svg','../../evil.svg'],['statistics','<td>11</td>','<td>12</td>']])test('rejects incorrect '+name,()=>assert.throws(()=>parseStandings(table().replace(from,to),NOW)));
test('complete regular-season format retains all 240 fixtures and explicit date-only precision',()=>{const d=parseMatches(schedule(),NOW);assert.equal(d.events.length,240);assert.equal(d.events[0].status,'scheduled');assert.equal(d.events[0].score.home,null);assert.equal(d.events[0].start_precision,'DATE_ONLY');assert.equal(d.events[0].source_date,'2026-10-10');assert.equal(d.events[0].details_available,false);assert.equal(d.teams.length,16);});
test('actual nil score survives with exact Belgrade kickoff conversion',()=>{const s=schedule().replace('10.10.2026','01.10.2026').replace('Planirano','Odigrano').replace('match-time">--:--','match-time">20:00').replace('match-result">:','match-result">0:0'),d=parseMatches(s,NOW);assert.deepEqual(d.events[0].score,{home:0,away:0});assert.equal(d.events[0].start_time,'2026-10-01T18:00:00.000Z');});
for(const [from,to] of [['kolo-30','kolo-31'],['Planirano','New status'],['Sezona 26/27','Sezona 27/28'],['match-result">:','match-result">2:1']])test('rejects malformed schedule '+from,()=>assert.throws(()=>parseMatches(schedule().replace(from,to),NOW)));
test('duplicate schedule identities fail closed',()=>assert.throws(()=>parseMatches(schedule().replace('kolo-30','kolo-29'),NOW)));
for(const [date,time,want] of [['10.10.2026','20:00','2026-10-10T18:00:00.000Z'],['10.11.2026','20:00','2026-11-10T19:00:00.000Z'],['03.04.2027','20:00','2027-04-03T18:00:00.000Z']])test('exact kickoff '+date,()=>assert.equal(kickoff(date,time,2026).start_time,want));
for(const [date,time] of [['31.02.2027','20:00'],['25.10.2026','02:30'],['28.03.2027','02:30'],['10.10.2026','25:00']])test('rejects ambiguous or invalid '+date+' '+time,()=>assert.throws(()=>kickoff(date,time,2026)));
test('date-only records never declare an invented exact kickoff timezone',()=>{const d=kickoff('10.10.2026','--:--',2026);assert.equal(d.source_timezone,null);assert.equal(d.start_precision,'DATE_ONLY');});
test('cache shares pending reads and retains old timestamp during source outage',async()=>{let now=NOW,fail=false,calls=[];const fetcher=async(url,opts)=>{calls.push({url,opts});if(fail)throw Error('offline');return response(url.endsWith('robots.txt')?'User-agent: *\nDisallow: /wp-admin/\n':table());};const load=officialLoader({fetcher,clock:()=>now}),[a,b]=await Promise.all([load('standings'),load('standings')]);assert.equal(a,b);assert.equal(calls.length,2);await load('standings');assert.equal(calls.length,2);now+=16*60000;fail=true;const old=await load('standings');assert.equal(old.stale,true);assert.equal(old.updated_at,a.updated_at);assert.equal(calls.length,3);await load('standings');assert.equal(calls.length,3);now+=25*3600000;await assert.rejects(load('standings'));assert(calls.every(c=>c.opts.credentials==='omit'&&c.opts.redirect==='error'&&c.url.startsWith(ORIGIN+'/')));});
test('robots denial and unknown view never fetch a source page',async()=>{let calls=0;const load=officialLoader({fetcher:async()=>{calls++;return response('User-agent: *\nDisallow: /sezona/',200,'text/plain');},clock:()=>NOW});await assert.rejects(load('standings'));assert.equal(calls,1);await assert.rejects(load('https://evil/'));assert.equal(calls,1);});
for(const [body,want] of [['User-agent: *\nDisallow: /',false],['User-agent: *\nDisallow: /wp-admin/',true],['User-agent: *\nDisallow: /sezona/*\nAllow: /sezona/tebela-takmicenja/$',true],['User-agent: NinkoSports-NewsData\nDisallow: /\nUser-agent: *\nAllow: /',false]])test('robots '+body,()=>assert.equal(robotAllows(body,PATHS.standings),want));
test('SPA routes assets compression and robots behavior remain intact',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'news-static-'));fs.mkdirSync(path.join(root,'assets'));const code='console.log("asset");'.repeat(200);fs.writeFileSync(path.join(root,'index.html'),'<!doctype html><title>NinkoSports</title>APP');fs.writeFileSync(path.join(root,'assets/app.js'),code);fs.writeFileSync(path.join(root,'robots.txt'),'User-agent: *');const calls=[],server=createNewsServer({root,loader:async view=>{calls.push(view);return {competition:{id:'serbia-prva-liga'},rows:[]};}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();fs.rmSync(root,{recursive:true,force:true});});const base='http://127.0.0.1:'+server.address().port;for(const route of ['/','/football/premier-league','/live-scores','/article/story','/sports/football','/not-a-real-route']){const r=await fetch(base+route);assert.equal(r.status,200);assert((await r.text()).includes('APP'));}const js=await fetch(base+'/assets/app.js',{headers:{'Accept-Encoding':'gzip'}});assert.equal(await js.text(),code);assert.equal(js.headers.get('content-encoding'),'gzip');assert.match(js.headers.get('content-type'),/javascript/);const robots=await fetch(base+'/robots.txt');assert.match(robots.headers.get('content-type'),/text\/plain/);assert.equal(await robots.text(),'User-agent: *');for(const route of ['/news-data/evil','/news-data/football/serbia-prva-liga/standings?url=http://127.0.0.1','/news-data/football/serbia-prva-liga/standings/'])assert.equal((await fetch(base+route)).status,404);assert.equal((await fetch(base+'/news-data/football/serbia-prva-liga/standings',{method:'POST'})).status,405);assert.equal(calls.length,0);for(const view of ['standings','matches']){const r=await fetch(base+'/news-data/football/serbia-prva-liga/'+view);assert.equal(r.status,200);assert.equal((await r.json()).competition.id,'serbia-prva-liga');}assert.deepEqual(calls,['standings','matches']);});
